addr: "0.0.0.0:8081"

db_url: "postgres://postgres:postgres@host.docker.internal:5433/order_db?sslmode=disable"

brokers:
  - "kafka1:9092"
  - "kafka2:9092"
  - "kafka3:9092"

topics:
  - "wb-orders"

group_id: "order-service-group-docker"

limit: 100
capacity: 1000
ttl: 5m